
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-21T12:33:24-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "bc7d01232354a2d9ff4631baa763e396e4466ce0",
 "version": "0.8.292"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
