
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-19T10:53:08-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "49ad17af59ff57a450c70b0ac34f74eb4405d948",
 "version": "1.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
