[tool.poetry]
name = "pypgstac"
version = "0.1.9"
description = ""
authors = ["David Bitner <bitner@dbspatial.com>"]
keywords = ["stac", "asyncpg"]
readme = "README"
homepage = "https://github.com/stac-utils/pgstac"
repository = "https://github.com/stac-utils/pgstac"
exclude = ["pypgstac/migrations/*.sql"]
include = ["pypgstac/migrations/pgstac*0.1.9.sql"]

[tool.poetry.dependencies]
python = "^3.8"
asyncpg = "^0.22.0"
smart-open = "^4.2.0"
typer = "^0.3.2"
asyncio = "^3.4.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
pypgstac = "pypgstac.pypgstac:app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
