name: Tests

on:
  push:
    branches:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install dev dependencies
        run: pip install pytest pytest-mypy-plugins
      - name: Setup package
        run: python setup.py develop
      - name: Run tests
        run: pytest tests/
