
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-21T10:36:38-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f78e4d299886d06a18e2d67f2274bf7e799f2c6a",
 "version": "2021.5.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
