
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-19T15:42:22+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "017843765d3df9728e86fa91833f0a53f09d218b",
 "version": "0.3.88"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
