
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-17T22:55:04+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "fa3d1b8fc63e01ccec2d6bc5fc32e6d05089ae0f",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
