
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-15T21:48:14+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "569804c6e5989d5d907bee8e5d6a0de678f3f7ef",
 "version": "0.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
