
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-21T10:58:26+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "4f2806b0d56b5e660b0d3f080101c1584042099a",
 "version": "2.6.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
