[tool.poetry]
name = "clean_auckland_gtfs"
version = "0.5.0"
description = "Python 3.8+ code for cleaning Auckland, New Zealand GTFS feeds"
authors = ["Alex Raichev <araichev@mrcagney.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8||^3.9"
gtfs_kit = ">=5"

[tool.poetry.dev-dependencies]
jupyter = "<2"
pytest = "^6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
