class pyezxl_enum:
	my_web_site = "www.halmoney.com"
	def __init__(self):
		self.line={
		"basic" : 1,
		"-" : -4115 ,
		"-." : 4,
		"-.." : 5,
		"." : -4118,
		"=" : -4119,
		"None" : -4142,
		"/." : 13,
		"continuous" : 1,
		"dash" : -4115 ,
		"dashdot" : 4,
		"dashdotdot" : 5,
		"dot" : -4118,
		"double" : -4119,
		"slantdashdot" : 13,
		"hairline" : 1,
		"thin" : 2,
		"medium" : -4138,
		"thick" : 4,
		"basic--" : 1,
		"basic-" : 2,
		"basic+" : -4138,
		"basic++" : 4,
		"diagonaldown" : 5,
		"diagonalup" : 6,
		"edgebottom" : 9,
		"edgeleft" : 7,
		"edgeright" : 10,
		"edgetop" : 10,
		"insidehorizontal" : 12,
		"insidevertical" : 11,
		"\\" : 5,
		"/" : 6,
		"bottom" : 9,
		"left" : 7,
		"right" : 10,
		"top" : 10,
		"bottom-in" : 12,
		"top-in" : 11,
		"rightleft-in" : 12,
		"leftright-in" : 5,
		}

		self.ez_orientation={
		"bottom" : -4170,
		"horizontal" : -4128,
		"up" : -4171,
		"vertical" : -4166,
		"downward" : -4170,
		"upward" : -4171,
		}

		self.copy={
		"pasteall" : -4104,
		"pasteallexceptborders" : 7,
		"pasteallmergingconditionalformats" : 14,
		"pasteallusingsourcetheme" : 13,
		"pastecolumnwidths" : 8,
		"pastecomments" : -4144,
		"pasteformats" : -4122,
		"pasteformulas" : -4123,
		"pasteformulasandnumberformats" : 11,
		"pastevalidation" : 6,
		"pastevalues" : -4163,
		"pastevaluesandnumberformats" : 12,
		"all" : -4104,
		"memo" : -4144,
		"format" : -4122,
		"formula" : -4123,
		"formula+format" : 11,
		"value" : -4163,
		"value+format" : 12,
		}

		self.letter={
		"a":"abcdefghijklmnopqrstuvwxyz",
		"ㄱ" :"ㄱㄴㄷㄹㅁㅂㅅㅇㅈㅊㅋㅌㅍㅎ",
		"가":"가나다라마바사아자차카타파하",
		"1":"1234567890",
		"그리스문자":"αβγδεζήθικλμνξόπρΣτ",
		"로마숫자":"ⅠⅡⅢⅣⅤⅥⅦⅧⅨⅩ",
		"원ㄱ":"㉠㉡㉢㉣㉤㉥㉦㉧㉨㉩㉪㉫㉬㉭",
		"원가":"㉮㉯㉰㉱㉲㉳㉴㉵㉶㉷㉸㉹㉺㉻",
		"원알":"ⒶⒷⒸⒹⒺⒻⒼⒽⒾⒿⓀⓁⓂⓃⓄⓅⓆⓇⓈⓉⓊⓋⓌⓍⓎⓏ",
		"원숫자":"⓪①②③④⑤⑥⑦⑧⑨⑩⑪⑫⑬⑭⑮⑯⑰⑱⑲⑳㉑㉒㉓㉔㉕㉖㉗㉘㉙㉚㉛㉜㉝㉞㉟㊱㊲㊳㊴㊵㊶㊷㊸㊹㊺㊻㊼㊽㊾㊿",
		}
