# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: d7_Sound.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='d7_Sound.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x64\x37_Sound.proto\"\x1e\n\x1c\x64\x37\x63\x31\x30\x30\x30_snd_adc_value_get_rq\"1\n\x1c\x64\x37\x63\x31\x30\x30\x30_snd_adc_value_get_ra\x12\x11\n\tadc_value\x18\x01 \x01(\rb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_D7C1000_SND_ADC_VALUE_GET_RQ = _descriptor.Descriptor(
  name='d7c1000_snd_adc_value_get_rq',
  full_name='d7c1000_snd_adc_value_get_rq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=48,
)


_D7C1000_SND_ADC_VALUE_GET_RA = _descriptor.Descriptor(
  name='d7c1000_snd_adc_value_get_ra',
  full_name='d7c1000_snd_adc_value_get_ra',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='adc_value', full_name='d7c1000_snd_adc_value_get_ra.adc_value', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=99,
)

DESCRIPTOR.message_types_by_name['d7c1000_snd_adc_value_get_rq'] = _D7C1000_SND_ADC_VALUE_GET_RQ
DESCRIPTOR.message_types_by_name['d7c1000_snd_adc_value_get_ra'] = _D7C1000_SND_ADC_VALUE_GET_RA

d7c1000_snd_adc_value_get_rq = _reflection.GeneratedProtocolMessageType('d7c1000_snd_adc_value_get_rq', (_message.Message,), dict(
  DESCRIPTOR = _D7C1000_SND_ADC_VALUE_GET_RQ,
  __module__ = 'd7_Sound_pb2'
  # @@protoc_insertion_point(class_scope:d7c1000_snd_adc_value_get_rq)
  ))
_sym_db.RegisterMessage(d7c1000_snd_adc_value_get_rq)

d7c1000_snd_adc_value_get_ra = _reflection.GeneratedProtocolMessageType('d7c1000_snd_adc_value_get_ra', (_message.Message,), dict(
  DESCRIPTOR = _D7C1000_SND_ADC_VALUE_GET_RA,
  __module__ = 'd7_Sound_pb2'
  # @@protoc_insertion_point(class_scope:d7c1000_snd_adc_value_get_ra)
  ))
_sym_db.RegisterMessage(d7c1000_snd_adc_value_get_ra)


# @@protoc_insertion_point(module_scope)
