[tool.poetry]
name = "solace"
version = "0.0.1"
description = "A modern microframework for building REST APIs in Python"
authors = ["Dan Sikes <dansikes7@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Werkzeug = "^2.0.0"
munch = "^2.5.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
