#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

install_requires = \
['mutagen', 'markdown']

entry_points = \
{'console_scripts': ['toc2audio = toc2audio:main']}

setup(name='toc2audio',
      version='1.0.0',
      description='Add Table of Contents and chapters to audio files',
      author='Jesús Cea Avión',
      author_email='jcea@jcea.es',
      url='https://docs.jcea.es/toc2audio/',
      py_modules=['toc2audio'],
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='>=3.6',
     )
