
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-17T17:12:38-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "01ee08a030b0b6b5f9033e18dc2b98711dd3c6a5",
 "version": "0.0.64"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
