
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-17T23:17:36-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ed7b31f1bd927b6171f0a4ba0e529b4cc3bd87eb",
 "version": "0.0.67"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
