[tool.poetry]
name = "fintix_modelcurator"
version = "0.1.13"
description = "helpers library used for model lab and model training and model deploying"
authors = ["Trinh Tran <trinhtran2151995@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.8"
tensorflow = "^2.4.1"
tensorflow-io = "^0.17.1"
scikit-learn = "^0.24.1"
pandas = "^1.2.4"
confluent-kafka = "^1.6.1"
PyYAML = "^5.4.1"
psycopg2-binary = "^2.8.6"
kafka-python = "^2.0.2"
xgboost = "1.4.1"
plotly = "4.14.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
