[tool.poetry]
name = "pycmp"
version = "0.1.3"
description = "Compiler MATLAB to Python"
authors = ["Artem Eroshev"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
ply = "3.11"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
mypy = "^0.812"
flake8 = "^3.9.2"
isort = "^5.8.0"
Sphinx = "^4.0.2"
coverage = "^5.5"
rinohtype = "^0.5.2"
wheel = "^0.36.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
