[tool.poetry]
name = "ghost-in-the-machine"
version = "0.0.63"
description = "Manage your digital presence"
authors = ["Angelo Gladding <angelo@lahacker.net>"]
license = "CC0-1.0"
readme = "README.md"
packages = [
    { include = "ghost.py" }
]

[tool.poetry.urls]
Homepage = "https://angelogladding.com/code/ghost"

[tool.poetry.plugins."web.apps"]
ghost = "ghost:app"

[tool.poetry.dependencies]
python = "^3.9"
understory = "^0.0.28"
# understory = {path = "../understory"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
