[tool.poetry]
name = "pyproteins"
version = "1.5.1"
description = "Toolbox to manipulate protein sequence data"
authors = ["glaunay <pitooon@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
bs4 = "^0.0.1"
biopython = "^1.78"
numpy = "^1.20.3"
lxml = "^4.6.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
