info = {"message": "Update version to 1.0.2", "commit": "f4fb29083cec2784839210277b02319ff00cc79c", "date": "2021-05-19 17:30:04 +0300", "branch": "release/1.0.2", "version": "1.0.1+97.gf4fb2908.dirty"}

# This file is automatically generated by version.py
# Do not include it to git!
