from typing import Any, Optional

from .monadic import Either as Either, Left as Left

def fetch(url: Any, timeout: int = ...) -> Any: ...
def fetch_xml_html(url: Any, parser: str = ..., timeout: int = ...) -> Any: ...
def fetch_json(url: Any, timeout: int = ...) -> Any: ...
def build_service_url(parts: Optional[Any] = ..., service_name: str = ...) -> Any: ...
def build_base_url(parts: Optional[Any] = ..., ark: Optional[Any] = ...) -> Any: ...
def build_url(parts: Any, quote_via: Any = ...) -> Any: ...
