
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-16T22:31:11-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "162d42f81c4247000aa2825e6c407f34f3250479",
 "version": "v0.20.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
