
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-22T19:12:40-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "7ad4fc187b2aff748bc9b19c49e257bee5ffecf0",
 "version": "0.0.69"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
