
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-14T18:26:11+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "82aa376895194daeb20e0370f887bb2f6a931002",
 "version": "v0.17a7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
