# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: d3_Servo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='d3_Servo.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x64\x33_Servo.proto\"j\n\x18\x64\x33\x63\x31\x30\x30\x30_srv_angle_set_rq\x12\x11\n\ttar_angle\x18\x01 \x01(\x11\x12\x15\n\rrotation_time\x18\x02 \x01(\r\x12\x16\n\x0eshielding_time\x18\x03 \x01(\r\x12\x0c\n\x04mode\x18\x04 \x01(\r\"\x1a\n\x18\x64\x33\x63\x31\x30\x30\x30_srv_angle_set_ra\"\'\n\x18\x64\x33\x63\x31\x30\x30\x31_srv_angle_get_rq\x12\x0b\n\x03pwr\x18\x01 \x01(\x08\"@\n\x18\x64\x33\x63\x31\x30\x30\x31_srv_angle_get_ra\x12\x11\n\tcur_angle\x18\x01 \x01(\x11\x12\x11\n\ttar_angle\x18\x02 \x01(\x11\"%\n\x16\x64\x33\x63\x31\x30\x30\x32_srv_pwm_set_rq\x12\x0b\n\x03pwm\x18\x01 \x01(\x11\"\x18\n\x16\x64\x33\x63\x31\x30\x30\x32_srv_pwm_set_ra\"#\n\x13\x64\x33\x63\x31\x30\x30\x34_srv_stop_rq\x12\x0c\n\x04mode\x18\x01 \x01(\r\"\x15\n\x13\x64\x33\x63\x31\x30\x30\x34_srv_stop_rab\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_D3C1000_SRV_ANGLE_SET_RQ = _descriptor.Descriptor(
  name='d3c1000_srv_angle_set_rq',
  full_name='d3c1000_srv_angle_set_rq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tar_angle', full_name='d3c1000_srv_angle_set_rq.tar_angle', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rotation_time', full_name='d3c1000_srv_angle_set_rq.rotation_time', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shielding_time', full_name='d3c1000_srv_angle_set_rq.shielding_time', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mode', full_name='d3c1000_srv_angle_set_rq.mode', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=124,
)


_D3C1000_SRV_ANGLE_SET_RA = _descriptor.Descriptor(
  name='d3c1000_srv_angle_set_ra',
  full_name='d3c1000_srv_angle_set_ra',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=152,
)


_D3C1001_SRV_ANGLE_GET_RQ = _descriptor.Descriptor(
  name='d3c1001_srv_angle_get_rq',
  full_name='d3c1001_srv_angle_get_rq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pwr', full_name='d3c1001_srv_angle_get_rq.pwr', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=193,
)


_D3C1001_SRV_ANGLE_GET_RA = _descriptor.Descriptor(
  name='d3c1001_srv_angle_get_ra',
  full_name='d3c1001_srv_angle_get_ra',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cur_angle', full_name='d3c1001_srv_angle_get_ra.cur_angle', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tar_angle', full_name='d3c1001_srv_angle_get_ra.tar_angle', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=259,
)


_D3C1002_SRV_PWM_SET_RQ = _descriptor.Descriptor(
  name='d3c1002_srv_pwm_set_rq',
  full_name='d3c1002_srv_pwm_set_rq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pwm', full_name='d3c1002_srv_pwm_set_rq.pwm', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=298,
)


_D3C1002_SRV_PWM_SET_RA = _descriptor.Descriptor(
  name='d3c1002_srv_pwm_set_ra',
  full_name='d3c1002_srv_pwm_set_ra',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=324,
)


_D3C1004_SRV_STOP_RQ = _descriptor.Descriptor(
  name='d3c1004_srv_stop_rq',
  full_name='d3c1004_srv_stop_rq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='d3c1004_srv_stop_rq.mode', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=361,
)


_D3C1004_SRV_STOP_RA = _descriptor.Descriptor(
  name='d3c1004_srv_stop_ra',
  full_name='d3c1004_srv_stop_ra',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=363,
  serialized_end=384,
)

DESCRIPTOR.message_types_by_name['d3c1000_srv_angle_set_rq'] = _D3C1000_SRV_ANGLE_SET_RQ
DESCRIPTOR.message_types_by_name['d3c1000_srv_angle_set_ra'] = _D3C1000_SRV_ANGLE_SET_RA
DESCRIPTOR.message_types_by_name['d3c1001_srv_angle_get_rq'] = _D3C1001_SRV_ANGLE_GET_RQ
DESCRIPTOR.message_types_by_name['d3c1001_srv_angle_get_ra'] = _D3C1001_SRV_ANGLE_GET_RA
DESCRIPTOR.message_types_by_name['d3c1002_srv_pwm_set_rq'] = _D3C1002_SRV_PWM_SET_RQ
DESCRIPTOR.message_types_by_name['d3c1002_srv_pwm_set_ra'] = _D3C1002_SRV_PWM_SET_RA
DESCRIPTOR.message_types_by_name['d3c1004_srv_stop_rq'] = _D3C1004_SRV_STOP_RQ
DESCRIPTOR.message_types_by_name['d3c1004_srv_stop_ra'] = _D3C1004_SRV_STOP_RA

d3c1000_srv_angle_set_rq = _reflection.GeneratedProtocolMessageType('d3c1000_srv_angle_set_rq', (_message.Message,), dict(
  DESCRIPTOR = _D3C1000_SRV_ANGLE_SET_RQ,
  __module__ = 'd3_Servo_pb2'
  # @@protoc_insertion_point(class_scope:d3c1000_srv_angle_set_rq)
  ))
_sym_db.RegisterMessage(d3c1000_srv_angle_set_rq)

d3c1000_srv_angle_set_ra = _reflection.GeneratedProtocolMessageType('d3c1000_srv_angle_set_ra', (_message.Message,), dict(
  DESCRIPTOR = _D3C1000_SRV_ANGLE_SET_RA,
  __module__ = 'd3_Servo_pb2'
  # @@protoc_insertion_point(class_scope:d3c1000_srv_angle_set_ra)
  ))
_sym_db.RegisterMessage(d3c1000_srv_angle_set_ra)

d3c1001_srv_angle_get_rq = _reflection.GeneratedProtocolMessageType('d3c1001_srv_angle_get_rq', (_message.Message,), dict(
  DESCRIPTOR = _D3C1001_SRV_ANGLE_GET_RQ,
  __module__ = 'd3_Servo_pb2'
  # @@protoc_insertion_point(class_scope:d3c1001_srv_angle_get_rq)
  ))
_sym_db.RegisterMessage(d3c1001_srv_angle_get_rq)

d3c1001_srv_angle_get_ra = _reflection.GeneratedProtocolMessageType('d3c1001_srv_angle_get_ra', (_message.Message,), dict(
  DESCRIPTOR = _D3C1001_SRV_ANGLE_GET_RA,
  __module__ = 'd3_Servo_pb2'
  # @@protoc_insertion_point(class_scope:d3c1001_srv_angle_get_ra)
  ))
_sym_db.RegisterMessage(d3c1001_srv_angle_get_ra)

d3c1002_srv_pwm_set_rq = _reflection.GeneratedProtocolMessageType('d3c1002_srv_pwm_set_rq', (_message.Message,), dict(
  DESCRIPTOR = _D3C1002_SRV_PWM_SET_RQ,
  __module__ = 'd3_Servo_pb2'
  # @@protoc_insertion_point(class_scope:d3c1002_srv_pwm_set_rq)
  ))
_sym_db.RegisterMessage(d3c1002_srv_pwm_set_rq)

d3c1002_srv_pwm_set_ra = _reflection.GeneratedProtocolMessageType('d3c1002_srv_pwm_set_ra', (_message.Message,), dict(
  DESCRIPTOR = _D3C1002_SRV_PWM_SET_RA,
  __module__ = 'd3_Servo_pb2'
  # @@protoc_insertion_point(class_scope:d3c1002_srv_pwm_set_ra)
  ))
_sym_db.RegisterMessage(d3c1002_srv_pwm_set_ra)

d3c1004_srv_stop_rq = _reflection.GeneratedProtocolMessageType('d3c1004_srv_stop_rq', (_message.Message,), dict(
  DESCRIPTOR = _D3C1004_SRV_STOP_RQ,
  __module__ = 'd3_Servo_pb2'
  # @@protoc_insertion_point(class_scope:d3c1004_srv_stop_rq)
  ))
_sym_db.RegisterMessage(d3c1004_srv_stop_rq)

d3c1004_srv_stop_ra = _reflection.GeneratedProtocolMessageType('d3c1004_srv_stop_ra', (_message.Message,), dict(
  DESCRIPTOR = _D3C1004_SRV_STOP_RA,
  __module__ = 'd3_Servo_pb2'
  # @@protoc_insertion_point(class_scope:d3c1004_srv_stop_ra)
  ))
_sym_db.RegisterMessage(d3c1004_srv_stop_ra)


# @@protoc_insertion_point(module_scope)
