# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: d8_Led.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='d8_Led.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x64\x38_Led.proto\"R\n\x1a\x64\x38\x63\x31\x30\x30\x30_led_fix_exp_set_rq\x12\x18\n\x10\x65xpressions_type\x18\x01 \x01(\r\x12\x0c\n\x04time\x18\x02 \x01(\r\x12\x0c\n\x04rgbc\x18\x03 \x01(\r\"\x1c\n\x1a\x64\x38\x63\x31\x30\x30\x30_led_fix_exp_set_ra\"\x91\x01\n\x16\x64\x38\x63\x31\x30\x30\x31_led_exp_set_rq\x12\x0c\n\x04time\x18\x01 \x01(\r\x12:\n\ncolor_lump\x18\x02 \x03(\x0b\x32&.d8c1001_led_exp_set_rq.dev_color_lump\x1a-\n\x0e\x64\x65v_color_lump\x12\r\n\x05index\x18\x01 \x01(\r\x12\x0c\n\x04rgbc\x18\x02 \x01(\r\"\x18\n\x16\x64\x38\x63\x31\x30\x30\x31_led_exp_set_rab\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_D8C1000_LED_FIX_EXP_SET_RQ = _descriptor.Descriptor(
  name='d8c1000_led_fix_exp_set_rq',
  full_name='d8c1000_led_fix_exp_set_rq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='expressions_type', full_name='d8c1000_led_fix_exp_set_rq.expressions_type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='d8c1000_led_fix_exp_set_rq.time', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rgbc', full_name='d8c1000_led_fix_exp_set_rq.rgbc', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=98,
)


_D8C1000_LED_FIX_EXP_SET_RA = _descriptor.Descriptor(
  name='d8c1000_led_fix_exp_set_ra',
  full_name='d8c1000_led_fix_exp_set_ra',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=128,
)


_D8C1001_LED_EXP_SET_RQ_DEV_COLOR_LUMP = _descriptor.Descriptor(
  name='dev_color_lump',
  full_name='d8c1001_led_exp_set_rq.dev_color_lump',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='d8c1001_led_exp_set_rq.dev_color_lump.index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rgbc', full_name='d8c1001_led_exp_set_rq.dev_color_lump.rgbc', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=276,
)

_D8C1001_LED_EXP_SET_RQ = _descriptor.Descriptor(
  name='d8c1001_led_exp_set_rq',
  full_name='d8c1001_led_exp_set_rq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='d8c1001_led_exp_set_rq.time', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='color_lump', full_name='d8c1001_led_exp_set_rq.color_lump', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_D8C1001_LED_EXP_SET_RQ_DEV_COLOR_LUMP, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=276,
)


_D8C1001_LED_EXP_SET_RA = _descriptor.Descriptor(
  name='d8c1001_led_exp_set_ra',
  full_name='d8c1001_led_exp_set_ra',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=302,
)

_D8C1001_LED_EXP_SET_RQ_DEV_COLOR_LUMP.containing_type = _D8C1001_LED_EXP_SET_RQ
_D8C1001_LED_EXP_SET_RQ.fields_by_name['color_lump'].message_type = _D8C1001_LED_EXP_SET_RQ_DEV_COLOR_LUMP
DESCRIPTOR.message_types_by_name['d8c1000_led_fix_exp_set_rq'] = _D8C1000_LED_FIX_EXP_SET_RQ
DESCRIPTOR.message_types_by_name['d8c1000_led_fix_exp_set_ra'] = _D8C1000_LED_FIX_EXP_SET_RA
DESCRIPTOR.message_types_by_name['d8c1001_led_exp_set_rq'] = _D8C1001_LED_EXP_SET_RQ
DESCRIPTOR.message_types_by_name['d8c1001_led_exp_set_ra'] = _D8C1001_LED_EXP_SET_RA

d8c1000_led_fix_exp_set_rq = _reflection.GeneratedProtocolMessageType('d8c1000_led_fix_exp_set_rq', (_message.Message,), dict(
  DESCRIPTOR = _D8C1000_LED_FIX_EXP_SET_RQ,
  __module__ = 'd8_Led_pb2'
  # @@protoc_insertion_point(class_scope:d8c1000_led_fix_exp_set_rq)
  ))
_sym_db.RegisterMessage(d8c1000_led_fix_exp_set_rq)

d8c1000_led_fix_exp_set_ra = _reflection.GeneratedProtocolMessageType('d8c1000_led_fix_exp_set_ra', (_message.Message,), dict(
  DESCRIPTOR = _D8C1000_LED_FIX_EXP_SET_RA,
  __module__ = 'd8_Led_pb2'
  # @@protoc_insertion_point(class_scope:d8c1000_led_fix_exp_set_ra)
  ))
_sym_db.RegisterMessage(d8c1000_led_fix_exp_set_ra)

d8c1001_led_exp_set_rq = _reflection.GeneratedProtocolMessageType('d8c1001_led_exp_set_rq', (_message.Message,), dict(

  dev_color_lump = _reflection.GeneratedProtocolMessageType('dev_color_lump', (_message.Message,), dict(
    DESCRIPTOR = _D8C1001_LED_EXP_SET_RQ_DEV_COLOR_LUMP,
    __module__ = 'd8_Led_pb2'
    # @@protoc_insertion_point(class_scope:d8c1001_led_exp_set_rq.dev_color_lump)
    ))
  ,
  DESCRIPTOR = _D8C1001_LED_EXP_SET_RQ,
  __module__ = 'd8_Led_pb2'
  # @@protoc_insertion_point(class_scope:d8c1001_led_exp_set_rq)
  ))
_sym_db.RegisterMessage(d8c1001_led_exp_set_rq)
_sym_db.RegisterMessage(d8c1001_led_exp_set_rq.dev_color_lump)

d8c1001_led_exp_set_ra = _reflection.GeneratedProtocolMessageType('d8c1001_led_exp_set_ra', (_message.Message,), dict(
  DESCRIPTOR = _D8C1001_LED_EXP_SET_RA,
  __module__ = 'd8_Led_pb2'
  # @@protoc_insertion_point(class_scope:d8c1001_led_exp_set_ra)
  ))
_sym_db.RegisterMessage(d8c1001_led_exp_set_ra)


# @@protoc_insertion_point(module_scope)
