[tool.poetry]
name = "onow"
version = "0.0.1"
description = "Tools for chatbot data science."
authors = ["Tangible AI <engineering@tangibleai.com>"]
license = "Hippocratic (MIT + Do No Harm)"

[tool.poetry.dependencies]
python = ">=3.7.1,<4.0"
pandas = "^1.2.4,<1.3.0"
scikit-learn = "^0.24.2,<0.25.0"
spacy = "^3.0.6,<3.1.0"
torchtext = "^0.9.1,<0.10.0"
torch = "^1.8.1,<1.9.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
