
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-15T15:35:49+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "02385f02e6753bd54b28b45e1632aaa62c68f7c0",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
