# auto-generated by pywriter.py: do not edit or commit
from openpower.decoder.isa.caller import ISACaller
from openpower.decoder.isa.bcd import bcd
from openpower.decoder.isa.branch import branch
from openpower.decoder.isa.comparefixed import comparefixed
from openpower.decoder.isa.condition import condition
from openpower.decoder.isa.fixedarith import fixedarith
from openpower.decoder.isa.fixedldstcache import fixedldstcache
from openpower.decoder.isa.fixedload import fixedload
from openpower.decoder.isa.fixedlogical import fixedlogical
from openpower.decoder.isa.fixedstore import fixedstore
from openpower.decoder.isa.fixedtrap import fixedtrap
from openpower.decoder.isa.simplev import simplev
from openpower.decoder.isa.sprset import sprset
from openpower.decoder.isa.stringldst import stringldst
from openpower.decoder.isa.system import system
from openpower.decoder.isa.fixedshift import fixedshift
from openpower.decoder.isa.fpstore import fpstore
from openpower.decoder.isa.fpload import fpload
from openpower.decoder.isa.fpmove import fpmove
from openpower.decoder.isa.fparith import fparith
from openpower.decoder.isa.fpcvt import fpcvt

class ISA(ISACaller, bcd, branch, comparefixed, condition, fixedarith, fixedldstcache, fixedload, fixedlogical, fixedstore, fixedtrap, simplev, sprset, stringldst, system, fixedshift, fpstore, fpload, fpmove, fparith, fpcvt):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instrs = {
            **self.bcd_instrs,
            **self.branch_instrs,
            **self.comparefixed_instrs,
            **self.condition_instrs,
            **self.fixedarith_instrs,
            **self.fixedldstcache_instrs,
            **self.fixedload_instrs,
            **self.fixedlogical_instrs,
            **self.fixedstore_instrs,
            **self.fixedtrap_instrs,
            **self.simplev_instrs,
            **self.sprset_instrs,
            **self.stringldst_instrs,
            **self.system_instrs,
            **self.fixedshift_instrs,
            **self.fpstore_instrs,
            **self.fpload_instrs,
            **self.fpmove_instrs,
            **self.fparith_instrs,
            **self.fpcvt_instrs,
        }
