# auto-generated by pywriter.py, do not edit or commit

from openpower.decoder.isa.caller import inject, instruction_info
from openpower.decoder.helpers import (EXTS, EXTS64, EXTZ64, ROTL64, ROTL32,
                                 MASK, MASK32,
                                 ne, eq, gt, ge, lt, le, ltu, gtu, length,
                                 trunc_divs, trunc_rems, MULS, DIVS, MODS,
                                 EXTS128, undefined,
                                 DOUBLE, SINGLE)
from openpower.decoder.selectable_int import SelectableInt
from openpower.decoder.selectable_int import selectconcat as concat
from openpower.decoder.orderedset import OrderedSet

class fpmove:

    @inject()
    def op_fmr(self, FRB):
        FRT = FRB[0:64]
        return (FRT,)

    @inject()
    def op_fmr_(self, FRB):
        FRT = FRB[0:64]
        return (FRT,)

    @inject()
    def op_fabs(self, FRB):
        FRT = concat(SelectableInt(value=0x0, bits=1), FRB[1:64])
        return (FRT,)

    @inject()
    def op_fabs_(self, FRB):
        FRT = concat(SelectableInt(value=0x0, bits=1), FRB[1:64])
        return (FRT,)

    @inject()
    def op_fnabs(self, FRB):
        FRT = concat(SelectableInt(value=0x1, bits=1), FRB[1:64])
        return (FRT,)

    @inject()
    def op_fnabs_(self, FRB):
        FRT = concat(SelectableInt(value=0x1, bits=1), FRB[1:64])
        return (FRT,)

    @inject()
    def op_fneg(self, FRB):
        FRT = concat(~FRB[0], FRB[1:64])
        return (FRT,)

    @inject()
    def op_fneg_(self, FRB):
        FRT = concat(~FRB[0], FRB[1:64])
        return (FRT,)

    @inject()
    def op_fcpsgn(self, FRA, FRB):
        FRT = concat(FRA[0], FRB[1:64])
        return (FRT,)

    @inject()
    def op_fcpsgn_(self, FRA, FRB):
        FRT = concat(FRA[0], FRB[1:64])
        return (FRT,)

    fpmove_instrs = {}
    fpmove_instrs['fmr'] = instruction_info(func=op_fmr,
                read_regs=OrderedSet(['FRB']),
                uninit_regs=OrderedSet(), write_regs=OrderedSet(['FRT']),
                special_regs=OrderedSet(), op_fields=OrderedSet(),
                form='X',
                asmregs=[['FRT', 'FRB'], '(Rc=0)'])
    fpmove_instrs['fmr.'] = instruction_info(func=op_fmr_,
                read_regs=OrderedSet(['FRB']),
                uninit_regs=OrderedSet(), write_regs=OrderedSet(['FRT']),
                special_regs=OrderedSet(), op_fields=OrderedSet(),
                form='X',
                asmregs=[['FRT', 'FRB'], '(Rc=0)'])
    fpmove_instrs['fabs'] = instruction_info(func=op_fabs,
                read_regs=OrderedSet(['FRB']),
                uninit_regs=OrderedSet(), write_regs=OrderedSet(['FRT']),
                special_regs=OrderedSet(), op_fields=OrderedSet(),
                form='X',
                asmregs=[['FRT', 'FRB'], '(Rc=0)'])
    fpmove_instrs['fabs.'] = instruction_info(func=op_fabs_,
                read_regs=OrderedSet(['FRB']),
                uninit_regs=OrderedSet(), write_regs=OrderedSet(['FRT']),
                special_regs=OrderedSet(), op_fields=OrderedSet(),
                form='X',
                asmregs=[['FRT', 'FRB'], '(Rc=0)'])
    fpmove_instrs['fnabs'] = instruction_info(func=op_fnabs,
                read_regs=OrderedSet(['FRB']),
                uninit_regs=OrderedSet(), write_regs=OrderedSet(['FRT']),
                special_regs=OrderedSet(), op_fields=OrderedSet(),
                form='X',
                asmregs=[['FRT', 'FRB'], '(Rc=0)'])
    fpmove_instrs['fnabs.'] = instruction_info(func=op_fnabs_,
                read_regs=OrderedSet(['FRB']),
                uninit_regs=OrderedSet(), write_regs=OrderedSet(['FRT']),
                special_regs=OrderedSet(), op_fields=OrderedSet(),
                form='X',
                asmregs=[['FRT', 'FRB'], '(Rc=0)'])
    fpmove_instrs['fneg'] = instruction_info(func=op_fneg,
                read_regs=OrderedSet(['FRB']),
                uninit_regs=OrderedSet(), write_regs=OrderedSet(['FRT']),
                special_regs=OrderedSet(), op_fields=OrderedSet(),
                form='X',
                asmregs=[['FRT', 'FRB'], '(Rc=0)'])
    fpmove_instrs['fneg.'] = instruction_info(func=op_fneg_,
                read_regs=OrderedSet(['FRB']),
                uninit_regs=OrderedSet(), write_regs=OrderedSet(['FRT']),
                special_regs=OrderedSet(), op_fields=OrderedSet(),
                form='X',
                asmregs=[['FRT', 'FRB'], '(Rc=0)'])
    fpmove_instrs['fcpsgn'] = instruction_info(func=op_fcpsgn,
                read_regs=OrderedSet(['FRA', 'FRB']),
                uninit_regs=OrderedSet(), write_regs=OrderedSet(['FRT']),
                special_regs=OrderedSet(), op_fields=OrderedSet(),
                form='X',
                asmregs=[['FRT', 'FRA', 'FRB'], '(Rc=0)'])
    fpmove_instrs['fcpsgn.'] = instruction_info(func=op_fcpsgn_,
                read_regs=OrderedSet(['FRA', 'FRB']),
                uninit_regs=OrderedSet(), write_regs=OrderedSet(['FRT']),
                special_regs=OrderedSet(), op_fields=OrderedSet(),
                form='X',
                asmregs=[['FRT', 'FRA', 'FRB'], '(Rc=0)'])
