# auto-generated by pywriter.py, do not edit or commit

from openpower.decoder.isa.caller import inject, instruction_info
from openpower.decoder.helpers import (EXTS, EXTS64, EXTZ64, ROTL64, ROTL32,
                                 MASK, MASK32,
                                 ne, eq, gt, ge, lt, le, ltu, gtu, length,
                                 trunc_divs, trunc_rems, MULS, DIVS, MODS,
                                 EXTS128, undefined,
                                 DOUBLE, SINGLE)
from openpower.decoder.selectable_int import SelectableInt
from openpower.decoder.selectable_int import selectconcat as concat
from openpower.decoder.orderedset import OrderedSet

class simplev:

    @inject()
    def op_setvl(self, RA, SVSTATE):
        VLimm = SVi + 1
        if eq(vs, 1):
            if ne(_RA, 0):
                VL = GPR.getz(_RA)[57:64]
            else:
                VL = VLimm[1:8]
        else:
            VL = SVSTATE[7:14]
        if eq(ms, 1):
            MVL = VLimm[1:8]
        else:
            MVL = SVSTATE[0:7]
        if gt(VL, MVL):
            eq(VL, MVL)
        SVSTATE[0:7] = MVL
        SVSTATE[7:14] = VL
        RT = concat(concat(0, repeat=57), VL)
        return (SVSTATE, RT,)

    @inject()
    def op_setvl_(self, RA, SVSTATE):
        VLimm = SVi + 1
        if eq(vs, 1):
            if ne(_RA, 0):
                VL = GPR.getz(_RA)[57:64]
            else:
                VL = VLimm[1:8]
        else:
            VL = SVSTATE[7:14]
        if eq(ms, 1):
            MVL = VLimm[1:8]
        else:
            MVL = SVSTATE[0:7]
        if gt(VL, MVL):
            eq(VL, MVL)
        SVSTATE[0:7] = MVL
        SVSTATE[7:14] = VL
        RT = concat(concat(0, repeat=57), VL)
        return (SVSTATE, RT,)

    simplev_instrs = {}
    simplev_instrs['setvl'] = instruction_info(func=op_setvl,
                read_regs=OrderedSet(['RA']),
                uninit_regs=OrderedSet(), write_regs=OrderedSet(['SVSTATE', 'RT']),
                special_regs=OrderedSet(['SVSTATE']), op_fields=OrderedSet(['SVi', 'vs', 'ms']),
                form='SVL',
                asmregs=[['RT', ''], 'RA,', 'SVi,', 'vs,', 'ms'])
    simplev_instrs['setvl.'] = instruction_info(func=op_setvl_,
                read_regs=OrderedSet(['RA']),
                uninit_regs=OrderedSet(), write_regs=OrderedSet(['SVSTATE', 'RT']),
                special_regs=OrderedSet(['SVSTATE']), op_fields=OrderedSet(['SVi', 'vs', 'ms']),
                form='SVL',
                asmregs=[['RT', ''], 'RA,', 'SVi,', 'vs,', 'ms'])
