# Workaround to bootstrap maturin on non-manylinux platforms
[build-system]
requires = ["setuptools~=53.0.0", "wheel~=0.36.2", "toml~=0.10.2"]
build-backend = "setuptools.build_meta"

[tool.maturin]
bindings = "bin"

[tool.black]
target_version = ['py36']
