
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-19T08:54:53-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "667531007af039b69bca047a38e9778e05727cc3",
 "version": "2021.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
