# Generated by Django 2.0.13 on 2021-04-03 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssettings',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_settings', to='books.Organization'),
        ),
        migrations.AlterField(
            model_name='financialsettings',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_settings', to='books.Organization'),
        ),
        migrations.AlterField(
            model_name='payrunsettings',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payrun_settings', to='books.Organization'),
        ),
    ]
