
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-21T13:45:25-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e9df5f3423cc16499cb34a08706ff7006c6f2957",
 "version": "v1.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
