
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-15T20:20:14+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "b095dbe8f7347cf5a3b62633a90d1ba26aa0af97",
 "version": "0.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
