[package]
name = "rusty-sieve"
version = "0.1.0"
authors = ["Tom Monks <t.m.w.monks@exeter.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rusty_sieve"
crate-type = ["cdylib"]

[dependencies.cpython]
version = "0.5"
features = ["extension-module"]

[dependencies]
