
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-19T15:40:45+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d582523f51ef47e03ea13059c7ca8fc8bcbe2ce4",
 "version": "0.7.109"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
