
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-17T17:02:11-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "db511489a3f82968446b165ec3bd60b34722587c",
 "version": "2.5.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
