
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-19T15:41:33+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "27f33616e804bcf6619e2448716467dd99f1330f",
 "version": "1.10.36"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
