
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-19T16:15:37+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4a4623e1eaec501c8648382e3a1942306f0414e3",
 "version": "0.9.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
