
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-22T17:46:52+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "de2f1e359e468f32a10f1b45267af3c2faa60b3c",
 "version": "0.1.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
