[tool.poetry]
name = "lessqlite"
version = "0.1.1"
description = "A less-like command-line tool for paging throufh SQLite databases."
authors = ["Dave VanderWeele <weele.me@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.0"
coveralls = "^3.0.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
Faker = "^8.1.4"
coverage = "^5.5"
dbml-sqlite = "^0.2.1"

[tool.poetry.scripts]
lessqlite = 'lessqlite.core:cli'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
