
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-14T14:17:24-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "c24c8362be587408a93aefafe1e4fcc509ef2c91",
 "version": "2021.05.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
