[tool.poetry]
name = "red_warden"
version = "0.1.0"
description = "Resilient, Extensible and Distributed Web Application Rapid Development ENgine"
authors = ["Daniele 'px' Picca <d.picca@sevenia.tech>"]

[tool.poetry.dependencies]
python = "^3.8"
uvicorn = {extras = ["standard"], version = "^0.13.4"}
gunicorn = "^20.1.0"
starlette = {extras = ["full"], version = "^0.14.2"}
Mako = "^1.1.4"
SQLAlchemy = "<1.4"
databases = {extras = ["mysql"], version = "^0.4.3"}
alembic = "^1.6.2"
aioredis = "^1.3.1"
motor = "^2.4.0"
cryptography = "^3.4.7"
httpx = "^0.18.1"
aioauth = "^0.1.6"
pedantic = "^1.2.7"


[tool.poetry.dev-dependencies]
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
