
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-15T15:52:14+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e24283641b1a2d5284862650c999edebb85ca44d",
 "version": "v1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
