[tool.poetry]
name = "ET-dot"
version = "0.0.1"
description = "<Enter a one-sentence description of this project here.>"
authors = ["Bert Tijskens <engelbert.tijskens@uantwerpen.be>"]
license = "MIT"

readme = 'README.rst'

repository = "https://github.com/etijskens/ET-dot"
homepage = "https://github.com/etijskens/ET-dot"

keywords = []

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.0.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
dotfiles = "et_dot:cli_dotfiles.main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
