
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-20T14:55:46+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "50e5a891b9ed54a998aa7cd20a92f0987dc0cc49",
 "version": "2.5.30.post.dev3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
