[tool.poetry]
name = "csv_edem"
version = "1.6.1"
description = "Treats CSV files exported from EDEM"
authors = ["Marcus Bruno Fernandes Silva <marcusbfs@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
matplotlib = "^3.4.2"
numpy = "^1.20.3"
openpyxl = "^3.0.7"
pandas = "^1.2.4"
XlsxWriter = "^1.4.3"
rich = "^10.2.0"
PySimpleGUI = "^4.41.2"

[tool.poetry.dev-dependencies]
pyinstaller = "^4.3"
mypy = "^0.812"
black = "^21.5b1"
isort = "^5.8.0"
autoflake = "^1.4"

[tool.poetry.scripts]
csv-edem-cli = "csv_edem.cli:main"
csv-edem-gui = "csv_edem.gui:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
