"""
    Diahook

    The Diahook server API documentation  # noqa: E501

    The version of the OpenAPI document: 0.8.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import diahook.openapi_client
from diahook.openapi_client.model.event_type_in_out import EventTypeInOut
globals()['EventTypeInOut'] = EventTypeInOut
from diahook.openapi_client.model.list_response_event_type_in_out import ListResponseEventTypeInOut


class TestListResponseEventTypeInOut(unittest.TestCase):
    """ListResponseEventTypeInOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListResponseEventTypeInOut(self):
        """Test ListResponseEventTypeInOut"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListResponseEventTypeInOut()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
