[tool.poetry]
name = "tatuarvela-magic"
version = "3.1.0"
description = "A tool for simplifying repeated command line tasks"
authors = ["Tatu Arvela <tatu.arvela@nitor.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/TatuArvela/Magic"
packages = [
    {include = "magic"}
]

[tool.poetry.dependencies]
click = "^8.0.0"
fastjsonschema = "^2.15.0"
python = "^3.9"

[tool.poetry.dev-dependencies]
bandit = "^1.7.0"
black = "^20.8b1"
coverage = "^5.5"
flake8 = "^3.8.4"
isort = "^5.7.0"
pre-commit = "^2.11.1"
pytest = "^6.2.3"
snapshottest = "^0.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
magic = "magic:main"

[tool.black]
exclude = '.*/snapshots/.*\.py'

[tool.isort]
profile = "black"
skip_gitignore = true
skip = ["tests/snapshots/"]

[tool.pytest]
# Put something here
