
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-17T16:33:47-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "fdb333578d4291732541ffd240b7c6f776ec4f3c",
 "version": "2021.5.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
