
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-18T12:51:51-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "2f58e67ea981fb36247ff8d49a3fdded75f21997",
 "version": "0.0.40"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
