
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-19T18:32:14-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "809ca3c37a4278b22681e5f6c6aa940661d9c011",
 "version": "v0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
