
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-14T12:15:47-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "d49314d3ed9f056c4d6a331e6e4d98e11c64078d",
 "version": "9.8.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
