
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-20T19:31:57+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "cd18dc44d682c89ed0cd5b35e0d234fb77ca00a6",
 "version": "1.6.0b6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
