
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-20T12:07:00+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "436827be19f9bf722922cfed39dc511fc0b793b3",
 "version": "2.5.30.post.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
