info = {"message": "Update version to 1.0.2 (#944)", "commit": "84de007435e05247c4366ee96d5c55737d24a103", "date": "2021-05-19 20:08:46 +0300", "branch": "master", "version": "1.0.1+97.g84de0074"}

# This file is automatically generated by version.py
# Do not include it to git!
