---
- name: my postgresql instances
  hosts: localhost
  tasks:
    - name: production instance
      postgresql_instance:
        name: prod
        state: started
        ssl: true
        configuration:
          port: 5433
          max_connections: 100
          shared_buffers: 1GB
          unix_socket_directories: /tmp

    - name: pre-production instance
      postgresql_instance:
        name: preprod
        state: started
        configuration:
          port: 5434
          unix_socket_directories: /tmp

    - name: dev instance, not running at the moment
      postgresql_instance:
        name: dev
        state: stopped
        configuration:
          port: 5444
          unix_socket_directories: /tmp
