[tool.poetry]
name = "ghost-in-the-machine"
version = "0.0.53"
description = "Manage your digital presence"
authors = ["Angelo Gladding <angelo@lahacker.net>"]
license = "CC-BY-4.0"
readme = "README.md"
packages = [
    { include = "ghost.py" }
]

[tool.poetry.urls]
Homepage = "https://angelogladding.com/code/ghost"

[tool.poetry.plugins."web.apps"]
ghost = "ghost:app"

[tool.poetry.dependencies]
python = "^3.9"
understory = "^0.0.27"
# understory = {path = "../understory"}
feedparser = "^6.0.2"
semver = "^2.13.0"

[tool.poetry.dev-dependencies]
ipython = "^7.23.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
