
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-29T16:58:42+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "119f522a0a67755090e5214d77534aa38ae15582",
 "version": "1.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
