#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['owlutils']

package_data = \
{'': ['*']}

setup(name='owlutils',
      version='0.1.0',
      description='Common utils used across owl company web apps',
      author='Shashank Kumar',
      author_email='me@shashankkumar.com',
      url='https://github.com/shashankkr9/owlutils',
      packages=packages,
      package_data=package_data,
      python_requires='>=3.7',
     )
