
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-22T18:34:16-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "1df3f5dd23b40cf0a2e99ebc29dd3c00e36f04bb",
 "version": "v1.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
