
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-20T07:49:05+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2a26d392fcce6760cc4bdce09c66a0f4dc49e8dd",
 "version": "0.0.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
