
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-19T15:31:34+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e50297a4c7cb22b5275eab4bbfef593a580cb9c5",
 "version": "0.7.104"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
