[build-system]
requires = ["setuptools_scm[toml]>=3.4.3", "setuptools-rust"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
local_scheme = "no-local-version"
write_to = "py_randomprime/version.py"