
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-22T17:20:16+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "8da7f84a65f662e2c0704f70578250d4d4635889",
 "version": "0.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
