
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-20T11:55:33+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "5d7f001e5be6ddc3e40174b70d44d4e7a9ad5789",
 "version": "2.5.30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
