
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-19T11:44:46-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2f00a0b03408d671a14bc5d5f35aa76f9a9262c0",
 "version": "0.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
