
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-18T11:23:46+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a70ac539b631455bbf0ce2623d3aff9b7154e6a6",
 "version": "0.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
