
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-20T22:40:17+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "27e5e3be9d165eaa09666103b30c25fc2fb0ab1c",
 "version": "0.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
