[tool.poetry]
name = "jaswdr_rid"
version = "0.1.0"
description = ""
authors = ["Jonathan Schweder <jonathanschweder@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.6.2,<4.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
isort = "^5.8.0"
black = "^21.5b1"
flake8 = "^3.9.2"
coverage = "^5.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
