
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-12T03:15:47+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d598e8cf8580ed434c77a22d9165a18a010f563d",
 "version": "v0.3.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
