[tool.poetry]
name = "understory-db"
version = "0.0.2"
description = "Tools for metamodern data management"
authors = ["Angelo Gladding <angelo@lahacker.net>"]
license = "AGPL-3.0-or-later"
readme = "README.md"
packages = [
    { include = "understory" }
]

[tool.poetry.urls]
Homepage = "https://github.com/canopy/understory-db"

[tool.poetry.dependencies]
python = "^3.7"
pendulum = "^2.1.2"
redis = "^3.5.3"
sh = "^1.14.2"
understory-fx = "^0.0.2"

[tool.poetry.dev-dependencies]
ipython = "^7.23.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
