
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-17T20:02:28-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "5edbc81ae63ff26544b3bd403b5c2648c39ac7f2",
 "version": "1.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
