[package]
name = "fastcrc"
version = "0.1.1"
authors = ["overcat <4catcode@gmail.com>"]
edition = "2018"
description = "A hyper-fast Python module for computing CRC(16, 32, 64) checksum"
license = "MIT License"
repository = "https://github.com/overcat/fastcrc"
homepage = "https://github.com/overcat/fastcrc"
readme = "README.rst"
keywords = ["crc", "crc16", "crc32", "crc64"]

[lib]
name = "fastcrc"
crate-type = ["cdylib"]

[dependencies]
crc = "2.0.0-rc.1"

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]