
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-22T16:56:49+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "76e31b3a9acde856d0fa4c3e9fc022f69786f891",
 "version": "0.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
