
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-16T02:51:49+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "eb91ba55abd6c319a6dfc499a4314f44de857710",
 "version": "0.6.dev2120"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
