
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-17T22:07:56-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "4979621e2b2f54ffd73ce3992c84d6b8943c5026",
 "version": "0.0.66"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
