# Generated by Django 3.1.7 on 2021-04-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210403_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='receipt_photo',
            field=models.FileField(blank=True, null=True, upload_to='receipt_photo/%Y/%m/%d/', verbose_name='Receipt photo'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='legal_name',
            field=models.CharField(help_text='Official name to appear on your reports,        sales invoices and bills', max_length=150),
        ),
    ]
