[tool.poetry]
name = "dt"
version = "0.1.0"
description = ""
authors = ["Vagiz Duseev <vagiz.duseev@dynatrace.com>"]

[tool.poetry.dependencies]
python = "^3.9"
ilexconf = "^0.9.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
