
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-20T10:37:51+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9415816f2d648256e1e22cf86ec33157dfdfc57d",
 "version": "0.9.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
