[tool.poetry]
name = "cesp"
version = "1.3.0"
description = "Converts blank space to underscore and other characters to avoid problems"
authors = ["Marcus Bruno Fernandes Silva <marcusbfs@gmail.com>"]
license = "MIT"
readme = "readme.md"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
black = "^21.5b1"
mypy = "^0.812"
isort = "^5.8.0"
autoflake = "^1.4"
py7zr = "^0.16.1"

[tool.poetry.scripts]
cesp = "cesp:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
