
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-20T22:50:25-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "c627e5bee3f6ffaafca7549eca5480287b7a78e5",
 "version": "0.8.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
