[tool.poetry]
name = "go-parallel"
version = "0.1.3"
description = "Utility function for running functions asynchronously."
authors = ["Indrajith Shetty <indrajitshetty@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
