
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-20T12:14:19+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2f4bff5997d0e3e021fc46e44765e26bdfc91d65",
 "version": "6.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
