[tool.poetry]
name = "beancount-ing-diba"
version = "0.5.0"
description = "Beancount Importer for ING-DiBa (DE) CSV exports"
readme = "README.md"
authors = ["Siddhant Goel <me@sgoel.dev>"]
license = "MIT"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Plugins",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Financial and Insurance Industry",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3 :: Only",
]
include = ["README.md", "License.txt"]
repository = "https://github.com/siddhantgoel/beancount-ing-diba"
keywords = ["banking", "beancount", "cli-accounting", "finance"]

[tool.black]
line-length = 79
skip-string-normalization = true

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
beancount = "^2.2"
flake8 = "^3.9"
pytest = "^6.2"
black = {version = "^21.5b0",python = ">=3.6.2,<4.0"}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
