
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-20T14:20:01-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5040617051ff68c93a4bf9c0682014b91a3aae6c",
 "version": "4.15.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
