info = {"message": "Make Storage export formats identical to regular JSON export (#762)", "commit": "8cfdc0e296a3725427f2ffa039509ea4b83efc82", "date": "2021-05-18 18:16:38 +0300", "branch": "master", "version": "1.0.1+91.g8cfdc0e2.dirty"}

# This file is automatically generated by version.py
# Do not include it to git!
