[tool.poetry]
name = "misty2py"
version = "3.0.2"
description = "A Python library for Misty II development"
authors = ["Chris 'Scar(R)ed' Vajdík <scarred.chris@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/ChrisScarred/misty2py"
repository = "https://github.com/ChrisScarred/misty2py"
classifiers = [
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ]
include = [
    "LICENSE",
    "changelog.md",
    "misty2py/allowed_actions.json",
    "misty2py/allowed_data.json",
    "misty2py/allowed_infos.json",
]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.25.1"
websocket-client = "^0.58.0"
pymitter = "^0.3.0"
python-dotenv = "^0.17.1"
keyboard = "^0.13.5"
pynput = "^1.7.3"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pytest = "^6.2.2"
Sphinx = "^3.5.4"
myst-parser = "^0.13.6"
recommonmark = "^0.7.1"
rinohtype = "^0.5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
