
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-18T18:25:02+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "b7f6b0c35742ee7acbfa21021e9f3c2acd51587a",
 "version": "0.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
