
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-20T11:33:16-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "8fc825e9d5e23bfc0f941b55b6a190db31ca6406",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
