
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-16T16:44:05-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "622bf8d4f8d06437cc2c11f241bac1ad0a7481e1",
 "version": "0.9.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
