[tool.poetry]
name = "understory"
version = "0.0.27"
description = "The tools that power the canopy"
authors = ["Angelo Gladding <angelo@lahacker.net>"]
license = "AGPL-3.0-or-later"
readme = "README.md"

[tool.poetry.urls]
Homepage = "https://github.com/canopy/understory"

[tool.poetry.scripts]
loveliness = "understory.loveliness:main"

[tool.poetry.dependencies]
python = "^3.7"
understory-web = "^0.0.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
