
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-20T15:47:33+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "68ad029918e4fd845f230e75d8a5da86bcc2af03",
 "version": "2.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
