
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-19T17:40:18+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0a1087f744367434181bfe157998a79f1a24a50a",
 "version": "0.12.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
