
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-14T10:42:52-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "8664b12a1eb5a39ed8076f7e3aeb96350b468023",
 "version": "5.0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
