
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-18T20:50:28+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d4cb8b6593d12b7a0192c54d339d3cd0f9bdfd35",
 "version": "0.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
