
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-18T22:36:33+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1bf0188a1e0cc1cf303104a5953b2f9f2a465ee4",
 "version": "0.12.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
