
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-20T12:15:55+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "dda63fbda71aefc5dd53fb1f8cc3b16f6cf747b9",
 "version": "2474"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
