[tool.poetry]
name = "double-stream-handler"
version = "0.1.0b1"
description = "A StreamHandler wrapper that outputs messages to different streams based on loglevel"
authors = ["Nikita Karamov <nick@karamoff.dev>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
black = { version = "^21.5b1", python = ">=3.6.2,<4.0" }
isort = "^5.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
known_first_party = "double_stream_handler"
src_paths = ["double_stream_handler", "tests"]
atomic = true
lines_after_imports = 2
lines_between_types = 1
