[tool.poetry]
name = "nicegui"
version = "v0.1.6"
description = "High-Level Abstraction Web-GUI Using Just Python"
authors = ["Zauberzeug GmbH"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/zauberzeug/nicegui"
keywords = ["gui", "ui", "web", "interface", "live"]

[tool.poetry.dependencies]
python = "^3.7"
justpy = "0.1.5"
matplotlib = "^3.4.1"
typing-extensions = "^3.10.0"

[tool.poetry.dev-dependencies]
icecream = "^2.1.0"
autopep8 = "^1.5.7"
debugpy = "^1.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
