
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-18T18:24:52-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "bac14a0ed46e88a8c3571b490c020da7f15495ba",
 "version": "0.0.68"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
