
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-21T10:02:41+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c26fb2832f52e8e8b2d14efabdc4876719e24fc1",
 "version": "0.4.36"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
