# Generated by Django 3.2 on 2021-05-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True, verbose_name='Subscribed to news letter')),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='Unsubscribe reason')),
            ],
            options={
                'verbose_name_plural': 'News Letter Subscriptions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
