[tool.poetry]
name = "ra-flatfile-importer"
version = "0.1.1"
description = "Flatfile importer for OS2mo/LoRa"
authors = ["Magenta <info@magenta.dk>"]
license = "MPL-2.0"
readme = "README.md"
homepage = "https://magenta.dk/"
repository = "https://git.magenta.dk/rammearkitektur/ra-flatfile-importer"
keywords = ["os2mo", "lora"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.1.2"
pydantic = "^1.8.1"
ramodels = "^0.3.3"
raclients = "^0.1.7"
tqdm = "^4.60.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
black = "^21.5b0"
flake8 = "^3.9.1"
mypy = "^0.812"
reorder-python-imports = "^2.5.0"
pre-commit = "^2.12.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
