
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-20T14:12:54+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "075472f473c8f51f3eab8de309f30f0beac36e50",
 "version": "2.5.30.post.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
