
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-20T08:44:49+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e6de22d5afdf732f2c87f736a35fd92c8b89ffa6",
 "version": "2021.1.post1.dev6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
