
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-14T14:21:57+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1df65b6075b1e140cc7a978305b50f4a3657d8de",
 "version": "0.16.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
