- project:
    templates:
      - nodejs6-jobs
      - publish-openstack-docs-pti
      - openstack-cover-jobs
      - openstack-python3-xena-jobs
    check:
      jobs:
        - refstack-tox-functional:
            nodeset: openstack-single-node-bionic
    gate:
      jobs:
        - refstack-tox-functional:
            nodeset: openstack-single-node-bionic

- job:
    name: refstack-tox-functional
    parent: openstack-tox
    description: |
      Run functional tests for an OpenStack Python project under cPython 3.
      Uses tox with the ``functional`` environment.
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
    vars:
      tox_envlist: functional
