name: tests

on:
  push:

jobs:
  tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - name: Clone vplot repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: vplot
          environment-file: environment.yml

      # TODO: Remove this step in production
      - name: Install vplanet-private pre-release
        shell: bash -l {0}
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          python -m pip install --no-deps git+https://$ACCESS_TOKEN@github.com/VirtualPlanetaryLaboratory/vplanet-private.git@b1594c1c8b714803248762ab7a4ea5a034c25c39#egg=vplanet

      - name: Install vplot
        shell: bash -l {0}
        run: |
          python -m pip install -U pip
          python -m pip install -e .

      - name: Run vplanet
        shell: bash -l {0}
        run: |
          for f in docs/notebooks/examples/*/vpl.in 
          do 
              pushd ${f%/*}
                  vplanet vpl.in
              popd
          done

      - name: Run tests
        shell: bash -l {0}
        run: python -m pytest -v tests --junitxml=junit/test-results.xml

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: junit/test-*.xml
          comment_mode: update last