from typing import Any, Dict, Optional

class Plugins:
    jenkins: Any = ...
    def __init__(self, jenkins: Any) -> None: ...
    async def get_all(self, depth: Optional[int]=...) -> Dict[str, dict]: ...
