
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-21T23:39:09+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "5a3c935f3780f7f9b3368d920c5ecd275d878143",
 "version": "v0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
