# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: d20_VisionModule.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='d20_VisionModule.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x16\x64\x32\x30_VisionModule.proto\"%\n#d20c1003_visionmodule_mid_offset_rq\"5\n#d20c1003_visionmodule_mid_offset_ra\x12\x0e\n\x06offset\x18\x01 \x01(\x02\"2\n!d20c1005_visionmodule_identify_rq\x12\r\n\x05model\x18\x01 \x01(\x11\"\xe7\x01\n!d20c1005_visionmodule_identify_ra\x12\r\n\x05model\x18\x01 \x01(\x11\x12>\n\x04info\x18\x02 \x03(\x0b\x32\x30.d20c1005_visionmodule_identify_ra.identify_info\x1as\n\ridentify_info\x12\x0b\n\x03tid\x18\x01 \x01(\x11\x12\r\n\x05tname\x18\x02 \x01(\t\x12\x0b\n\x03\x65id\x18\x03 \x01(\x11\x12\r\n\x05\x65name\x18\x04 \x01(\t\x12\t\n\x01x\x18\x05 \x01(\r\x12\t\n\x01y\x18\x06 \x01(\r\x12\t\n\x01w\x18\x07 \x01(\r\x12\t\n\x01h\x18\x08 \x01(\r\"6\n%d20c1008_visionmodule_model_switch_rq\x12\r\n\x05model\x18\x01 \x01(\x11\"7\n%d20c1008_visionmodule_model_switch_ra\x12\x0e\n\x06result\x18\x01 \x01(\x11\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_D20C1003_VISIONMODULE_MID_OFFSET_RQ = _descriptor.Descriptor(
  name='d20c1003_visionmodule_mid_offset_rq',
  full_name='d20c1003_visionmodule_mid_offset_rq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=63,
)


_D20C1003_VISIONMODULE_MID_OFFSET_RA = _descriptor.Descriptor(
  name='d20c1003_visionmodule_mid_offset_ra',
  full_name='d20c1003_visionmodule_mid_offset_ra',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset', full_name='d20c1003_visionmodule_mid_offset_ra.offset', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=118,
)


_D20C1005_VISIONMODULE_IDENTIFY_RQ = _descriptor.Descriptor(
  name='d20c1005_visionmodule_identify_rq',
  full_name='d20c1005_visionmodule_identify_rq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='d20c1005_visionmodule_identify_rq.model', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=170,
)


_D20C1005_VISIONMODULE_IDENTIFY_RA_IDENTIFY_INFO = _descriptor.Descriptor(
  name='identify_info',
  full_name='d20c1005_visionmodule_identify_ra.identify_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tid', full_name='d20c1005_visionmodule_identify_ra.identify_info.tid', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tname', full_name='d20c1005_visionmodule_identify_ra.identify_info.tname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eid', full_name='d20c1005_visionmodule_identify_ra.identify_info.eid', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ename', full_name='d20c1005_visionmodule_identify_ra.identify_info.ename', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='d20c1005_visionmodule_identify_ra.identify_info.x', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='d20c1005_visionmodule_identify_ra.identify_info.y', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='w', full_name='d20c1005_visionmodule_identify_ra.identify_info.w', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='h', full_name='d20c1005_visionmodule_identify_ra.identify_info.h', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=404,
)

_D20C1005_VISIONMODULE_IDENTIFY_RA = _descriptor.Descriptor(
  name='d20c1005_visionmodule_identify_ra',
  full_name='d20c1005_visionmodule_identify_ra',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='d20c1005_visionmodule_identify_ra.model', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='info', full_name='d20c1005_visionmodule_identify_ra.info', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_D20C1005_VISIONMODULE_IDENTIFY_RA_IDENTIFY_INFO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=404,
)


_D20C1008_VISIONMODULE_MODEL_SWITCH_RQ = _descriptor.Descriptor(
  name='d20c1008_visionmodule_model_switch_rq',
  full_name='d20c1008_visionmodule_model_switch_rq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='d20c1008_visionmodule_model_switch_rq.model', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=460,
)


_D20C1008_VISIONMODULE_MODEL_SWITCH_RA = _descriptor.Descriptor(
  name='d20c1008_visionmodule_model_switch_ra',
  full_name='d20c1008_visionmodule_model_switch_ra',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='d20c1008_visionmodule_model_switch_ra.result', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=462,
  serialized_end=517,
)

_D20C1005_VISIONMODULE_IDENTIFY_RA_IDENTIFY_INFO.containing_type = _D20C1005_VISIONMODULE_IDENTIFY_RA
_D20C1005_VISIONMODULE_IDENTIFY_RA.fields_by_name['info'].message_type = _D20C1005_VISIONMODULE_IDENTIFY_RA_IDENTIFY_INFO
DESCRIPTOR.message_types_by_name['d20c1003_visionmodule_mid_offset_rq'] = _D20C1003_VISIONMODULE_MID_OFFSET_RQ
DESCRIPTOR.message_types_by_name['d20c1003_visionmodule_mid_offset_ra'] = _D20C1003_VISIONMODULE_MID_OFFSET_RA
DESCRIPTOR.message_types_by_name['d20c1005_visionmodule_identify_rq'] = _D20C1005_VISIONMODULE_IDENTIFY_RQ
DESCRIPTOR.message_types_by_name['d20c1005_visionmodule_identify_ra'] = _D20C1005_VISIONMODULE_IDENTIFY_RA
DESCRIPTOR.message_types_by_name['d20c1008_visionmodule_model_switch_rq'] = _D20C1008_VISIONMODULE_MODEL_SWITCH_RQ
DESCRIPTOR.message_types_by_name['d20c1008_visionmodule_model_switch_ra'] = _D20C1008_VISIONMODULE_MODEL_SWITCH_RA

d20c1003_visionmodule_mid_offset_rq = _reflection.GeneratedProtocolMessageType('d20c1003_visionmodule_mid_offset_rq', (_message.Message,), dict(
  DESCRIPTOR = _D20C1003_VISIONMODULE_MID_OFFSET_RQ,
  __module__ = 'd20_VisionModule_pb2'
  # @@protoc_insertion_point(class_scope:d20c1003_visionmodule_mid_offset_rq)
  ))
_sym_db.RegisterMessage(d20c1003_visionmodule_mid_offset_rq)

d20c1003_visionmodule_mid_offset_ra = _reflection.GeneratedProtocolMessageType('d20c1003_visionmodule_mid_offset_ra', (_message.Message,), dict(
  DESCRIPTOR = _D20C1003_VISIONMODULE_MID_OFFSET_RA,
  __module__ = 'd20_VisionModule_pb2'
  # @@protoc_insertion_point(class_scope:d20c1003_visionmodule_mid_offset_ra)
  ))
_sym_db.RegisterMessage(d20c1003_visionmodule_mid_offset_ra)

d20c1005_visionmodule_identify_rq = _reflection.GeneratedProtocolMessageType('d20c1005_visionmodule_identify_rq', (_message.Message,), dict(
  DESCRIPTOR = _D20C1005_VISIONMODULE_IDENTIFY_RQ,
  __module__ = 'd20_VisionModule_pb2'
  # @@protoc_insertion_point(class_scope:d20c1005_visionmodule_identify_rq)
  ))
_sym_db.RegisterMessage(d20c1005_visionmodule_identify_rq)

d20c1005_visionmodule_identify_ra = _reflection.GeneratedProtocolMessageType('d20c1005_visionmodule_identify_ra', (_message.Message,), dict(

  identify_info = _reflection.GeneratedProtocolMessageType('identify_info', (_message.Message,), dict(
    DESCRIPTOR = _D20C1005_VISIONMODULE_IDENTIFY_RA_IDENTIFY_INFO,
    __module__ = 'd20_VisionModule_pb2'
    # @@protoc_insertion_point(class_scope:d20c1005_visionmodule_identify_ra.identify_info)
    ))
  ,
  DESCRIPTOR = _D20C1005_VISIONMODULE_IDENTIFY_RA,
  __module__ = 'd20_VisionModule_pb2'
  # @@protoc_insertion_point(class_scope:d20c1005_visionmodule_identify_ra)
  ))
_sym_db.RegisterMessage(d20c1005_visionmodule_identify_ra)
_sym_db.RegisterMessage(d20c1005_visionmodule_identify_ra.identify_info)

d20c1008_visionmodule_model_switch_rq = _reflection.GeneratedProtocolMessageType('d20c1008_visionmodule_model_switch_rq', (_message.Message,), dict(
  DESCRIPTOR = _D20C1008_VISIONMODULE_MODEL_SWITCH_RQ,
  __module__ = 'd20_VisionModule_pb2'
  # @@protoc_insertion_point(class_scope:d20c1008_visionmodule_model_switch_rq)
  ))
_sym_db.RegisterMessage(d20c1008_visionmodule_model_switch_rq)

d20c1008_visionmodule_model_switch_ra = _reflection.GeneratedProtocolMessageType('d20c1008_visionmodule_model_switch_ra', (_message.Message,), dict(
  DESCRIPTOR = _D20C1008_VISIONMODULE_MODEL_SWITCH_RA,
  __module__ = 'd20_VisionModule_pb2'
  # @@protoc_insertion_point(class_scope:d20c1008_visionmodule_model_switch_ra)
  ))
_sym_db.RegisterMessage(d20c1008_visionmodule_model_switch_ra)


# @@protoc_insertion_point(module_scope)
