# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dB_TouchSwitch.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dB_TouchSwitch.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x14\x64\x42_TouchSwitch.proto\"\x19\n\x17\x64\x62\x63\x31\x30\x30\x31_tch_type_get_rq\"\'\n\x17\x64\x62\x63\x31\x30\x30\x31_tch_type_get_ra\x12\x0c\n\x04type\x18\x01 \x01(\rb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DBC1001_TCH_TYPE_GET_RQ = _descriptor.Descriptor(
  name='dbc1001_tch_type_get_rq',
  full_name='dbc1001_tch_type_get_rq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=49,
)


_DBC1001_TCH_TYPE_GET_RA = _descriptor.Descriptor(
  name='dbc1001_tch_type_get_ra',
  full_name='dbc1001_tch_type_get_ra',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='dbc1001_tch_type_get_ra.type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['dbc1001_tch_type_get_rq'] = _DBC1001_TCH_TYPE_GET_RQ
DESCRIPTOR.message_types_by_name['dbc1001_tch_type_get_ra'] = _DBC1001_TCH_TYPE_GET_RA

dbc1001_tch_type_get_rq = _reflection.GeneratedProtocolMessageType('dbc1001_tch_type_get_rq', (_message.Message,), dict(
  DESCRIPTOR = _DBC1001_TCH_TYPE_GET_RQ,
  __module__ = 'dB_TouchSwitch_pb2'
  # @@protoc_insertion_point(class_scope:dbc1001_tch_type_get_rq)
  ))
_sym_db.RegisterMessage(dbc1001_tch_type_get_rq)

dbc1001_tch_type_get_ra = _reflection.GeneratedProtocolMessageType('dbc1001_tch_type_get_ra', (_message.Message,), dict(
  DESCRIPTOR = _DBC1001_TCH_TYPE_GET_RA,
  __module__ = 'dB_TouchSwitch_pb2'
  # @@protoc_insertion_point(class_scope:dbc1001_tch_type_get_ra)
  ))
_sym_db.RegisterMessage(dbc1001_tch_type_get_ra)


# @@protoc_insertion_point(module_scope)
