
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-18T15:44:01+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "220ff04f2c51dddd80bdd67b4e70fbcacc2a4b6b",
 "version": "4.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
