# Generated by Django 2.0.13 on 2021-03-31 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.Client', verbose_name='To Client'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='books.Organization', verbose_name='From Organization'),
        ),
        migrations.AddField(
            model_name='expenseclaimline',
            name='expense_claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='books.ExpenseClaim'),
        ),
        migrations.AddField(
            model_name='expenseclaimline',
            name='tax_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.TaxRate'),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.Employee', verbose_name='Paid by employee'),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_claims', to='books.Organization', verbose_name='From Organization'),
        ),
        migrations.AddField(
            model_name='estimateline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='books.Estimate'),
        ),
        migrations.AddField(
            model_name='estimateline',
            name='tax_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.TaxRate'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.Client', verbose_name='To Client'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimates', to='books.Organization', verbose_name='From Organization'),
        ),
        migrations.AddField(
            model_name='billline',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='books.Bill'),
        ),
        migrations.AddField(
            model_name='billline',
            name='tax_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.TaxRate'),
        ),
        migrations.AddField(
            model_name='bill',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.Client', verbose_name='From Client'),
        ),
        migrations.AddField(
            model_name='bill',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='books.Organization', verbose_name='To Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('number', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='expenseclaim',
            unique_together={('number', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='estimate',
            unique_together={('number', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('number', 'organization')},
        ),
    ]
