
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-08T14:23:09+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9bc41c11ce350ebd8a4dc0d88b07db2a7f7a7afa",
 "version": "0.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
