
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-17T13:24:48-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b15a2381598929b6e81ab497dc6a60ed1035274c",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
