
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-20T09:23:31+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7714d50610ac0ec38c3541b93f63e34d8b2f88e4",
 "version": "v2021.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
