[tool.poetry]
name = "double-stream-handler"
version = "1.0.0"
description = "A StreamHandler wrapper that outputs messages to different streams based on logLevel"
license = "BSD-3-Clause"
authors = ["Nikita Karamov <nick@karamoff.dev>"]
readme = "README.md"
repository = "https://github.com/NickKaramoff/DoubleStreamHandler/"
keywords = [
    "logging",
    "handler",
    "StreamHandler"
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Environment :: Plugins",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Logging"
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/NickKaramoff/DoubleStreamHandler/issues"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
black = { version = "^21.5b1", python = ">=3.6.2,<4.0" }
isort = "^5.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
known_first_party = "double_stream_handler"
src_paths = ["double_stream_handler", "tests"]
atomic = true
lines_after_imports = 2
lines_between_types = 1
