
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-17T15:44:22+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "daa62921adde1fe5d1f47ea9ad0a18109b1bc513",
 "version": "0.4.26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
