
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-19T14:42:01+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9282145cae32fa1ed0886badac75e3ca146e8cf3",
 "version": "1.6.0b5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
